package com.paykeyfear.vpn.protocols.vless

import com.paykeyfear.vpn.core.Protector
import java.lang.reflect.Method
import timber.log.Timber

/**
 * Reflective bridge to the gomobile-generated `vlessmobile.Vlessmobile` Java
 * class produced by `third_party/vless-mobile`. Mirrors [AwgNative] in
 * spirit: when `vless.aar` is absent (fresh checkout, JVM tests), this
 * object reports unavailable and the VLESS tunnel falls back to noop.
 *
 * Expected Java signatures (generated by `gomobile bind`):
 * ```
 * package vlessmobile;
 * public class Vlessmobile {
 *     public static int    StartXray(String configJson);
 *     public static void   StopXray(int handle);
 *     public static int    Tun2SocksStart(int tunFd, String host, int port);
 *     public static void   Tun2SocksStop(int handle);
 *     public static void   SetProtector(Protector p);   // Go interface
 *     public static String LastError();
 *     public static String Version();
 * }
 * public interface Protector { boolean protect(int fd); }
 * ```
 */
internal object VlessNative {
    private val bridge: Bridge? = runCatching {
        val cls = Class.forName("paykeyfearnative.Paykeyfearnative")
        val protectorCls = Class.forName("paykeyfearnative.Protector")
        Bridge(
            startXray = cls.getMethod("VlessStartXray", String::class.java),
            stopXray = cls.getMethod("VlessStopXray", Int::class.javaPrimitiveType),
            t2sStart = cls.getMethod(
                "VlessTun2SocksStart",
                Int::class.javaPrimitiveType,
                String::class.java,
                Int::class.javaPrimitiveType,
            ),
            t2sStop = cls.getMethod("VlessTun2SocksStop", Int::class.javaPrimitiveType),
            setProtector = cls.getMethod("SetProtector", protectorCls),
            lastError = cls.getMethod("VlessLastError"),
            protectorCls = protectorCls,
        )
    }.onFailure {
        Timber.tag(TAG).d("paykeyfearnative.aar not on classpath (%s) — running in noop mode", it.javaClass.simpleName)
    }.getOrNull()

    val NATIVE_AVAILABLE: Boolean get() = bridge != null

    fun installProtector(protector: Protector) {
        val b = bridge ?: return
        val proxy = java.lang.reflect.Proxy.newProxyInstance(
            b.protectorCls.classLoader,
            arrayOf(b.protectorCls),
        ) { _, method, args ->
            if (method.name == "protect" && args != null && args.isNotEmpty()) {
                protector.protect((args[0] as Int))
            } else {
                true
            }
        }
        b.setProtector.invoke(null, proxy)
    }

    fun startXray(configJson: String): Int {
        val b = bridge ?: return INVALID_HANDLE
        val h = b.startXray.invoke(null, configJson) as Int
        if (h <= 0) {
            Timber.tag(TAG).e("VlessStartXray failed: %s", b.lastError.invoke(null))
            return INVALID_HANDLE
        }
        return h
    }

    fun stopXray(handle: Int) {
        bridge?.stopXray?.invoke(null, handle)
    }

    fun tun2socksStart(tunFd: Int, host: String, port: Int): Int {
        val b = bridge ?: return INVALID_HANDLE
        val h = b.t2sStart.invoke(null, tunFd, host, port) as Int
        if (h <= 0) {
            Timber.tag(TAG).e("VlessTun2SocksStart failed: %s", b.lastError.invoke(null))
            return INVALID_HANDLE
        }
        return h
    }

    fun tun2socksStop(handle: Int) {
        bridge?.t2sStop?.invoke(null, handle)
    }

    private class Bridge(
        val startXray: Method,
        val stopXray: Method,
        val t2sStart: Method,
        val t2sStop: Method,
        val setProtector: Method,
        val lastError: Method,
        val protectorCls: Class<*>,
    )

    const val INVALID_HANDLE: Int = -1
    private const val TAG = "VlessNative"
}
