// Code generated by gobind. DO NOT EDIT.

// Java class vlessmobile.Vlessmobile is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/paykeyfear/proxylink-android/third_party/vless-mobile
package vlessmobile;

import go.Seq;

public abstract class Vlessmobile {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Vlessmobile() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyProtector implements Seq.Proxy, Protector {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyProtector(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native boolean protect(int fd);
	}
	
	
	/**
	 * LastError returns the most recent Start error message, or empty string.
	Stays available even after the handle that produced the error is gone.
	 */
	public static native String lastError();
	/**
	 * SetProtector registers the Android protect() callback. Safe to call
	multiple times; the most recent value wins. Must be called before
	StartXray when running on Android.
	 */
	public static native void setProtector(Protector p0);
	/**
	 * StartXray boots Xray-core with the given JSON config. The config is
	expected to contain exactly one SOCKS5 inbound on 127.0.0.1 — the port
	chosen by the caller (Kotlin XrayConfigBuilder) and re-used by
	Tun2SocksStart. Returns a handle (&gt;0) or -1 on error.
	 */
	public static native int startXray(String configJson);
	/**
	 * StopXray releases all resources associated with the handle. No-op if the
	handle is unknown.
	 */
	public static native void stopXray(int handle);
	/**
	 * Tun2SocksStart pumps packets between a Linux TUN file descriptor and a
	local SOCKS5 endpoint. socksHost is typically &#34;127.0.0.1&#34;.
	
	Returns a handle (&gt;0) or -1 on error. The handle is independent of the
	StartXray handle — caller should track both.
	 */
	public static native int tun2SocksStart(int tunFd, String socksHost, int socksPort);
	/**
	 * Tun2SocksStop stops the packet pump for the given handle. No-op if unknown.
	 */
	public static native void tun2SocksStop(int handle);
	/**
	 * Version returns a human-readable build stamp for About screens.
	 */
	public static native String version();
}
