package com.paykeyfear.vpn.protocols.awg

import java.lang.reflect.Method
import timber.log.Timber

/**
 * Bridge to the gomobile-generated `awgmobile.Awgmobile` Java class.
 *
 * Uses reflection so the Kotlin module compiles whether or not
 * `protocols/awg/libs/awg.aar` (built from `third_party/awg-mobile`) is
 * present on the classpath. When the class is missing (fresh checkout,
 * JVM unit tests), [available] is false and [AwgTunnel] falls back to
 * its noop path.
 *
 * Expected Java signature (generated by `gomobile bind`):
 * ```
 * package awgmobile;
 * public class Awgmobile {
 *     public static int    Start(String cfg, int tunFd);
 *     public static void   Stop(int handle);
 *     public static String GetStats(int handle);
 *     public static String GetVersion();
 *     public static String LastError();
 * }
 * ```
 */
internal object AwgNative {
    private val bridge: Bridge? = runCatching {
        val cls = Class.forName("awgmobile.Awgmobile")
        val protectorCls = Class.forName("awgmobile.Protector")
        Bridge(
            start = cls.getMethod("Start", String::class.java, Int::class.javaPrimitiveType),
            stop = cls.getMethod("Stop", Int::class.javaPrimitiveType),
            stats = cls.getMethod("GetStats", Int::class.javaPrimitiveType),
            lastError = cls.getMethod("LastError"),
            setProtector = cls.getMethod("SetProtector", protectorCls),
            protectorCls = protectorCls,
        )
    }.onFailure {
        Timber.tag(TAG).d("awg.aar not on classpath (%s) — running in noop mode", it.javaClass.simpleName)
    }.getOrNull()

    val NATIVE_AVAILABLE: Boolean get() = bridge != null

    fun installProtector(protector: com.paykeyfear.vpn.core.Protector) {
        val b = bridge ?: return
        val proxy = java.lang.reflect.Proxy.newProxyInstance(
            b.protectorCls.classLoader,
            arrayOf(b.protectorCls),
        ) { _, method, args ->
            if (method.name == "protect" && args != null && args.isNotEmpty()) {
                protector.protect(args[0] as Int)
            } else {
                true
            }
        }
        b.setProtector.invoke(null, proxy)
    }

    fun startTunnel(config: String, tunFd: Int): Long {
        val b = bridge ?: return AwgTunnel.INVALID_HANDLE
        val h = (b.start.invoke(null, config, tunFd) as Int)
        if (h <= 0) {
            Timber.tag(TAG).e("awgmobile.Start failed: %s", b.lastError.invoke(null))
            return AwgTunnel.INVALID_HANDLE
        }
        return h.toLong()
    }

    fun stopTunnel(handle: Long) {
        bridge?.stop?.invoke(null, handle.toInt())
    }

    fun getStats(handle: Long): LongArray {
        val raw = bridge?.stats?.invoke(null, handle.toInt()) as? String ?: return longArrayOf(0, 0)
        var rx = 0L
        var tx = 0L
        raw.lineSequence().forEach { line ->
            when {
                line.startsWith("rx=") -> rx = line.substringAfter("rx=").trim().toLongOrNull() ?: 0
                line.startsWith("tx=") -> tx = line.substringAfter("tx=").trim().toLongOrNull() ?: 0
            }
        }
        return longArrayOf(rx, tx)
    }

    private class Bridge(
        val start: Method,
        val stop: Method,
        val stats: Method,
        val lastError: Method,
        val setProtector: Method,
        val protectorCls: Class<*>,
    )

    private const val TAG = "AwgNative"
}
