build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    active: true
    threshold: 250
  CyclomaticComplexMethod:
    active: true
    threshold: 25
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    active: true
    thresholdInClasses: 30
    thresholdInFiles: 30

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 5
  WildcardImport:
    active: true
  MaxLineLength:
    active: false
  UnusedPrivateProperty:
    active: false

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*'
    excludes: ['**/test/**', '**/androidTest/**']
  PackageNaming:
    active: false
  MatchingDeclarationName:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
