package com.paykeyfear.vpn.protocols.hysteria2

import com.paykeyfear.vpn.core.Protector
import java.lang.reflect.Method
import timber.log.Timber

/**
 * Reflective bridge to the gomobile-generated `hy2mobile.Hy2mobile` Java
 * class produced by `third_party/hysteria2-mobile`. Mirrors [com.paykeyfear
 * .vpn.protocols.vless.VlessNative] in spirit: when `hysteria.aar` is
 * absent (fresh checkout, JVM tests), this object reports unavailable and
 * the Hysteria2 tunnel falls back to noop.
 *
 * Expected Java signatures (generated by `gomobile bind`):
 * ```
 * package hy2mobile;
 * public class Hy2mobile {
 *     public static String Start(String yamlConfig, int tunFd);  // returns handle
 *     public static void   Stop(String handle);
 *     public static String Stats(String handle);                 // {"rx":..,"tx":..}
 *     public static void   SetProtector(Protector p);            // Go interface
 *     public static String LastError();
 *     public static String Version();
 * }
 * public interface Protector { boolean protect(int fd); }
 * ```
 */
internal object Hysteria2Native {
    private val bridge: Bridge? = runCatching {
        val cls = Class.forName("hy2mobile.Hy2mobile")
        val protectorCls = Class.forName("hy2mobile.Protector")
        Bridge(
            start = cls.getMethod(
                "Start",
                String::class.java,
                Int::class.javaPrimitiveType,
            ),
            stop = cls.getMethod("Stop", String::class.java),
            stats = cls.getMethod("Stats", String::class.java),
            setProtector = cls.getMethod("SetProtector", protectorCls),
            lastError = cls.getMethod("LastError"),
            protectorCls = protectorCls,
        )
    }.onFailure {
        Timber.tag(TAG).d(
            "hysteria.aar not on classpath (%s) — running in noop mode",
            it.javaClass.simpleName,
        )
    }.getOrNull()

    val NATIVE_AVAILABLE: Boolean get() = bridge != null

    fun installProtector(protector: Protector) {
        val b = bridge ?: return
        val proxy = java.lang.reflect.Proxy.newProxyInstance(
            b.protectorCls.classLoader,
            arrayOf(b.protectorCls),
        ) { _, method, args ->
            if (method.name == "protect" && args != null && args.isNotEmpty()) {
                protector.protect(args[0] as Int)
            } else {
                true
            }
        }
        b.setProtector.invoke(null, proxy)
    }

    /** Returns the Go-side handle string, or null on failure (LastError logged). */
    fun start(yamlConfig: String, tunFd: Int): String? {
        val b = bridge ?: return null
        val handle = b.start.invoke(null, yamlConfig, tunFd) as? String
        if (handle.isNullOrEmpty()) {
            Timber.tag(TAG).e("hy2mobile.Start failed: %s", b.lastError.invoke(null))
            return null
        }
        return handle
    }

    fun stop(handle: String) {
        bridge?.stop?.invoke(null, handle)
    }

    /** Returns (rx,tx) parsed from the JSON the Go side emits, zeros if unknown. */
    fun stats(handle: String): LongArray {
        val b = bridge ?: return longArrayOf(0L, 0L)
        val raw = (b.stats.invoke(null, handle) as? String).orEmpty()
        if (raw.isEmpty()) return longArrayOf(0L, 0L)
        return parseStatsJson(raw)
    }

    internal fun parseStatsJson(raw: String): LongArray {
        // Tiny ad-hoc parser: avoids pulling kotlinx.serialization into the
        // protocol module just to read two integers.
        val rx = extractLong(raw, "\"rx\"")
        val tx = extractLong(raw, "\"tx\"")
        return longArrayOf(rx, tx)
    }

    private fun extractLong(raw: String, key: String): Long {
        val idx = raw.indexOf(key)
        if (idx < 0) return 0L
        var i = idx + key.length
        while (i < raw.length && raw[i] != ':') i++
        if (i >= raw.length) return 0L
        i++
        while (i < raw.length && raw[i].isWhitespace()) i++
        val start = i
        while (i < raw.length && (raw[i].isDigit() || (i == start && raw[i] == '-'))) i++
        return raw.substring(start, i).toLongOrNull() ?: 0L
    }

    private class Bridge(
        val start: Method,
        val stop: Method,
        val stats: Method,
        val setProtector: Method,
        val lastError: Method,
        val protectorCls: Class<*>,
    )

    private const val TAG = "Hysteria2Native"
}
